django/edirtic/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('maincourante.urls')),
]

django/maincourante/urls.py
from django.conf import settings
from django.urls import include, path

from tastypie.api import Api

from . import views
from .api import EvenementResource, IndicatifResource, MessageResource

v1_api = Api(api_name='v1')
v1_api.register(EvenementResource())
v1_api.register(IndicatifResource())
v1_api.register(MessageResource())

urlpatterns = [
    path('api/', include(v1_api.urls)),
    # Evenement
    path('', views.EvenementListView.as_view(), name='list-evenements'),
    path('add/', views.EvenementCreateView.as_view(), name='add-evenement'),
    path('<slug:evenement>/report/', views.evenement_report, name='report'),
    path('<slug:evenement>/manage/', views.evenement_manage, name='manage-evenement'),
    path('<slug:evenement>/manage/cloture/', views.evenement_cloture, name='cloture-evenement'),
    path('<slug:evenement>/manage/indicatifs/', views.indicatif_list, name='list-indicatifs'),
    path('<slug:evenement>/manage/indicatifs/<int:indicatif>/delete', views.indicatif_delete, name='delete-indicatif'),
    # Indicatifs
    path('<slug:evenement>/indicatifs/', views.indicatif_search, name='search-indicatif'),
]

if settings.ANGULAR:
    urlpatterns += [
        # Live
        path('<slug:evenement>/live/', views.evenement_live_angular, name='live'),
        # Message
        path('<slug:evenement>/', views.message_angular, name='add-message'),
    ]
else:
    urlpatterns += [
        # Live
        path('<slug:evenement>/live/', views.evenement_live, name='live'),
        # Message
        path('<slug:evenement>/', views.message_add, name='add-message'),
        path('<slug:evenement>/message/<int:message>/edit/', views.message_edit, name='edit-message'),
        path('<slug:evenement>/message/<int:message>/delete/', views.message_delete, name='delete-message'),
        path('<slug:evenement>/message/last/', views.message_last, name='last-messages'),
    ]

django/maincourante/models.py
from django.contrib.auth.models import User
from django.db.models import PROTECT, BooleanField, CharField, DateTimeField, ForeignKey, Model, TextField
from django.urls import reverse

from autoslug import AutoSlugField

MAX_LENGTH = 100

__all__ = ['User', 'Evenement', 'Indicatif', 'MessageThread', 'MessageVersion', 'MessageSuppression']


class TimeStampedModel(Model):
    cree = DateTimeField('créé', auto_now_add=True, editable=False)
    modifie = DateTimeField('modifié', auto_now=True, editable=False)


class Evenement(TimeStampedModel):
    class Meta:
        ordering = ['clos', 'cree']

    nom = CharField(max_length=MAX_LENGTH)
    slug = AutoSlugField(populate_from='nom', unique=True)
    clos = BooleanField(default=False)

    def __str__(self):
        return '%s%s' % (self.nom, ' (clos)' if self.clos else '')

    def get_absolute_url(self):
        return reverse('add-message', args=[self.slug])


class Indicatif(Model):
    class Meta:
        ordering = ['nom']
        unique_together = ['evenement', 'nom']

    evenement = ForeignKey(Evenement, on_delete=PROTECT)
    nom = CharField(max_length=32)
    deleted = BooleanField(default=False)

    def __str__(self):
        return self.nom


class MessageSuppression(TimeStampedModel):

    operateur = ForeignKey(User, on_delete=PROTECT)
    raison = TextField()


class MessageThread(Model):
    class Meta:
        ordering = ['-pk']

    evenement = ForeignKey(Evenement, on_delete=PROTECT)
    suppression = ForeignKey(MessageSuppression, null=True, on_delete=PROTECT)

    @property
    def modified(self):
        return self.versions.count() > 1

    @property
    def deleted(self):
        return self.suppression is not None

    @property
    def last_version(self):
        return self.versions.last()

    @property
    def cree(self):
        return self.versions.first().cree

    @property
    def modifie(self):
        return self.last_version.cree

    @property
    def operateur(self):
        return self.last_version.operateur

    @property
    def expediteur(self):
        return self.last_version.expediteur

    @property
    def destinataire(self):
        return self.last_version.destinataire

    @property
    def corps(self):
        return self.last_version.corps

    def __str__(self):
        return str(self.last_version)


class MessageVersion(TimeStampedModel):
    class Meta:
        ordering = ['pk']

    thread = ForeignKey(MessageThread, related_name='versions', on_delete=PROTECT)
    operateur = ForeignKey(User, on_delete=PROTECT)
    expediteur = ForeignKey(Indicatif, related_name='+', on_delete=PROTECT)
    destinataire = ForeignKey(Indicatif, related_name='+', on_delete=PROTECT)
    corps = TextField()

    def __str__(self):
        return "[%s → %s] %s" % (self.expediteur, self.destinataire, self.corps)

django/maincourante/forms.py
from django import forms
from django.forms.models import modelform_factory

from .models import MAX_LENGTH, Indicatif

__all__ = ['IndicatifForm', 'ClotureForm', 'MessageForm', 'EditMessageForm', 'DeleteMessageForm']


IndicatifForm = modelform_factory(Indicatif, fields=['nom'])


class MessageForm(forms.Form):

    destinataire = forms.CharField(max_length=MAX_LENGTH)
    expediteur = forms.CharField(max_length=MAX_LENGTH)
    corps = forms.CharField()
    reponse = forms.CharField(required=False)


class EditMessageForm(forms.Form):

    corps = forms.CharField(max_length=256,
            label="Message")


class DeleteMessageForm(forms.Form):

    raison = forms.CharField(max_length=256,
            label="Veuillez indiquer la raison de cette suppression")


class ClotureForm(forms.Form):

    def __init__(self, evenement, *args, **kwargs):
        super(ClotureForm, self).__init__(*args, **kwargs)
        self.evenement = evenement

    def clean_nom(self):
        nom = self.cleaned_data['nom']
        if nom != self.evenement.nom:
            raise forms.ValidationError("Vous n’avez pas rentré le nom de l’évènement correctement.")

    nom = forms.CharField(max_length=MAX_LENGTH)

django/maincourante/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, render_to_response
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, ListView

from braces.views import LoginRequiredMixin

from .forms import ClotureForm, DeleteMessageForm, EditMessageForm, IndicatifForm, MessageForm
from .models import Evenement, Indicatif, MessageSuppression, MessageThread, MessageVersion

##############
# Evenements #
##############


class EvenementListView(LoginRequiredMixin, ListView):
    model = Evenement


class EvenementCreateView(LoginRequiredMixin, CreateView):
    model = Evenement
    fields = ['nom']


@login_required
def evenement_manage(request, evenement):

    if evenement.clos:
        raise PermissionDenied

    return redirect(reverse('cloture-evenement', args=[evenement.slug]))


@login_required
def evenement_cloture(request, evenement):

    if evenement.clos:
        raise PermissionDenied

    form = ClotureForm(evenement, request.POST or None)

    if request.method == 'POST' and form.is_valid():
        evenement.clos = True
        evenement.save()
        return redirect(reverse('report', args=[evenement.slug]))

    return render(request, 'maincourante/evenement_cloture.html', {
        'form': form,
    })


@login_required
def evenement_report(request, evenement):

    return render(request, 'maincourante/evenement_report.html', {
        'msgs': MessageThread.objects.filter(evenement=evenement),
    })


@login_required
def evenement_live(request, evenement):

    messages = MessageThread.objects.filter(evenement=evenement).all()[:10]
    return render(request, 'maincourante/evenement_live.html', {
        'msgs': messages,
    })


@login_required
def evenement_live_angular(request, evenement):

    messages = MessageThread.objects.filter(evenement=evenement).all()[:10]
    return render(request, 'maincourante/evenement_live_angular.html', {
        'messages': messages,
    })


############
# Messages #
############


@login_required
def message_add(request, evenement, message=None):

    form = MessageForm(request.POST or None)
    edit_form = EditMessageForm()
    delete_form = DeleteMessageForm()

    if request.method == 'POST' and form.is_valid():

        expediteur, destinataire = (Indicatif.objects.get_or_create(evenement=evenement, nom=form.cleaned_data[nom])[0]
                                    for nom in ['expediteur', 'destinataire'])
        thread = MessageThread(evenement=evenement)
        thread.save()
        MessageVersion(
            thread=thread,
            operateur=request.user,
            expediteur=expediteur,
            destinataire=destinataire,
            corps=form.cleaned_data['corps']).save()

        reponse = form.cleaned_data['reponse']
        if reponse:
            thread = MessageThread(evenement=evenement)
            thread.save()
            MessageVersion(
                thread=thread, operateur=request.user, expediteur=destinataire, destinataire=expediteur,
                corps=reponse).save()

        return redirect(reverse('add-message', args=[evenement.slug]))

    return render(
        request, 'maincourante/message_add.html', {
            'msgs': MessageThread.objects.filter(evenement=evenement).all()[:10],
            'add_form': form,
            'edit_form': edit_form,
            'delete_form': delete_form,
        })


@login_required
def message_edit(request, evenement, message):

    thread = get_object_or_404(MessageThread, evenement=evenement, id=message)

    if thread.deleted:
        raise Http404

    form = EditMessageForm(request.POST)

    if form.is_valid():

        # TODO: modifier aussi l’expéditeur et le destinataire
        event = MessageVersion(
            thread=thread,
            operateur=request.user,
            expediteur=thread.expediteur,
            destinataire=thread.destinataire,
            corps=form.cleaned_data['corps'])
        event.save()

    return redirect(reverse('add-message', args=[evenement.slug]))


@login_required
@require_http_methods(["POST"])
def message_delete(request, evenement, message):

    thread = get_object_or_404(MessageThread, evenement=evenement, id=message)

    if thread.deleted:
        raise Http404

    form = DeleteMessageForm(request.POST)

    if form.is_valid():

        suppression = MessageSuppression(operateur=request.user, raison=form.cleaned_data['raison'])
        suppression.save()
        thread.suppression = suppression
        thread.save()

    return redirect(reverse('add-message', args=[evenement.slug]))


@login_required
def message_last(request, evenement):

    deleted = request.GET.get('deleted')
    if deleted:
        deleted = deleted == '1'
    else:
        deleted = True

    history = request.GET.get('history')
    if history:
        history = history == '1'
    else:
        history = True

    tools = request.GET.get('tools')
    if tools:
        tools = tools == '1'
    else:
        tools = False

    messages = MessageThread.objects.filter(evenement=evenement).all()[:10]

    c = {
        'evenement': evenement,
        'messages': messages,
        'show_deleted': deleted,
        'show_history': history,
        'show_tools': tools,
    }

    return render_to_response('maincourante/tags/messages.html', context=c)


##############
# Indicatifs #
##############


@login_required
def indicatif_list(request, evenement):

    if evenement.clos:
        raise PermissionDenied

    form = IndicatifForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        indicatif = form.save(commit=False)
        indicatif.evenement = evenement
        indicatif.save()
        return redirect(reverse('list-indicatifs', args=[evenement.slug]))

    return render(request, 'maincourante/indicatif_list.html', {
        'indicatifs': Indicatif.objects.filter(evenement=evenement),
        'form': form,
    })


@login_required
def indicatif_delete(request, evenement, indicatif):

    if evenement.clos:
        raise PermissionDenied

    indicatif = get_object_or_404(Indicatif, pk=indicatif, deleted=False)

    indicatif.deleted = True
    indicatif.save()

    return redirect(reverse('list-indicatifs', args=[evenement.slug]))


@login_required
def indicatif_search(request, evenement):

    term = request.GET.get('query')
    if not term:
        raise Http404

    indicatifs = Indicatif.objects.filter(evenement=evenement, deleted=False, nom__istartswith=term)[:10]

    response = []
    for indicatif in indicatifs:
        response += [{
            'value': indicatif.nom,
            'data': indicatif.nom,
        }]

    c = {
        'suggestions': response,
    }

    return JsonResponse(c, safe=False)


###########
# Angular #
###########


@login_required
def message_angular(request, evenement):

    return render(request, 'maincourante/message_angular.html')

django/maincourante/templates/maincourante/base.html
{% extends 'base.html' %}

{% block navbar-left %}
    <li role="presentation" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ evenement.nom }}&#160;<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="{% url 'list-evenements' %}"><span class="glyphicon glyphicon-list"></span> Liste des évènements</a>
            </li>
            {% if user_is_operator %}
            <li class="divider"></li>
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="{% url 'add-evenement' %}"><span class="glyphicon glyphicon-plus"></span> Créer un évènement</a>
            </li>
            {% endif %}
        </ul>
    </li>
    {% if not evenement.clos %}
    {% if user_is_operator %}
    <li role="presentation"{% block saisitab %}{% endblock %}><a tabindex="-1" href="{% url 'add-message' evenement.slug %}">Saisie</a></li>
    {% endif %}
    <li role="presentation"{% block livetab %}{% endblock %}><a tabindex="-1" href="{% url 'live' evenement.slug %}">Live</a></li>
    {% endif %}
    <li role="presentation"{% block reporttab %}{% endblock %}><a tabindex="-1" href="{% url 'report' evenement.slug %}">Compte rendu</a></li>
    {% if not evenement.clos %}
    {% if user_is_operator %}
    <li role="presentation"{% block managetab %}{% endblock %}><a tabindex="-1" href="{% url 'manage-evenement' evenement.slug %}">Gestion</a></li>
    {% endif %}
    {% endif %}
{% endblock %}

django/maincourante/templates/maincourante/evenement_cloture.html
{% extends 'maincourante/evenement_manage.html' %}

{% load bootstrap3 %}

{% block cloturetab %}primary{% endblock %}

{% block content %}

{{ block.super }}

<div class="panel panel-danger">
	<div class="panel-heading">
		<h3>Cloturer l’évènement</h3>
	</div>
    <div class="panel-body">
        <p>
            Êtes vous vraiment SÛR de vouloir cloturer l’évènement « {{ evenement.nom }} » ?
            Il ne sera alors plus possible d’effecuter une quelconque modification.
        </p>
        <p>Pour valider la cloture de cet évènement, veuillez rentrer son nom puis valider avec le bouton « Cloturer l’évènement ».</p>
        <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            {% bootstrap_form form layout="horizontal" %}
            {% buttons layout="horizontal" %}
            <button type="submit" class="btn btn-danger">Cloturer l’évènement</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

django/maincourante/templates/maincourante/evenement_form.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}

<div class="panel panel-primary">
	<div class="panel-heading">
		<h3>Créer un évènement</h3>
	</div>
    <div class="panel-body">
        <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            {% bootstrap_form form layout="horizontal" %}
            {% buttons layout="horizontal" %}
            <button type="submit" class="btn btn-primary">Créer</button>
            <a href="{% url 'list-evenements' %}" class="btn btn-default">Annuler</a>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

django/maincourante/templates/maincourante/evenement_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="text-right">
    <img src="{% static 'img/logo-crf.png' %}" />
</div>

{% regroup evenement_list by clos as evenement_grouper %}
{% for evenement_group in evenement_grouper %}
<h2>Évènements {% if evenement_group.grouper %}passés{% else %}en cours{% endif %}</h2>
<ul class="list-group">
    {% for evenement in evenement_group.list %}
    <a class="list-group-item" href="{% url 'add-message' evenement.slug %}">
        <h4>{{ evenement }}</h4>
    </a>
    {% empty %}
    <li class="list-group-item"><em>Aucun évènement {% if evenemnt_group.grouper %}passé{% else %}en cours{% endif %}.</em></li>
    {% endfor %}
</ul>
{% if not forloop.last %}<hr />{% endif %}
{% endfor %}
{% endblock %}

django/maincourante/templates/maincourante/evenement_live.html
{% extends 'maincourante/base.html' %}

{% load message_tags %}

{% block livetab %} class="active"{% endblock %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h1>{{ evenement.nom }}</h1>
    </div>
</div>

<div id="messages-content">
{% render_messages msgs show_deleted=False show_history=False %}
</div>
{% endblock %}

{% block js_end %}
{{ block.super }}
<script type="text/javascript">
window.setInterval(function() {
    $.get("{% url 'last-messages' evenement.slug %}?deleted=0&history=0", function(data, status) {
        $("#messages-content").html(data);
    });
}, 5000);
</script>
{% endblock %}

django/maincourante/templates/maincourante/indicatif_list.html
{% extends 'maincourante/evenement_manage.html' %}

{% load bootstrap3 %}

{% block indicatiftab %}primary{% endblock %}

{% block content %}

{{ block.super }}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Ajouter un indicatif</h3>
    </div>
    <div class="panel-body">
        <form action="" method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group">
                <label class="sr-only" for="id_nom">Nom</label>
                <input class="form-control" id="id_nom" maxlength="32" name="nom" placeholder="Nom" required="required" title="" type="text" autofocus />
            </div>
            {% buttons layout="inline" %}
            <button type="submit" class="btn btn-primary">Ajouter</button>
            {% endbuttons %}
        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Liste des indicatifs</h3>
    </div>
    {% if indicatifs %}
    <ul class="list-group">
        {% for indicatif in indicatifs %}
        <li class="list-group-item">
            {{ indicatif }}
            {% if not indicatif.deleted %}
            <a href="{% url 'delete-indicatif' evenement.slug indicatif.pk %}" class="pull-right btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="panel-body">
        <em>Aucun indicatif.</em>
    </div>
    {% endif %}
</div>

{% endblock %}

django/maincourante/templates/maincourante/message_add.html
{% extends 'maincourante/base.html' %}

{% load static %}
{% load bootstrap3 %}
{% load message_tags %}

{% block saisitab %} class="active"{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/autocomplete.css' %}">
{% endblock %}

{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>Saisie des messages</h4>
    </div>
    <div class="panel-body">
        <form method="post" class="form-horizontal">
            {% csrf_token %}
			<div class="form-group">
			    <label class="col-md-3 control-label" for="id_destinataire">Destinataire</label>
                <div class="col-md-6">
                    <input class="form-control" id="id_destinataire" maxlength="100" name="destinataire" placeholder="Destinataire" required="required" title="" type="text" autofocus />
                </div>
            </div>
			<div class="form-group">
			    <label class="col-md-3 control-label" for="id_expediteur">Expéditeur</label>
                <div class="col-md-6">
                    <input class="form-control" id="id_expediteur" maxlength="100" name="expediteur" placeholder="Expéditeur" required="required" title="" type="text" />
                </div>
            </div>
			<div class="form-group">
			    <label class="col-md-3 control-label" for="id_corps">Message</label>
                <div class="col-md-6">
                    <input class="form-control" id="id_corps" name="corps" placeholder="Message" required="required" title="" type="text" />
                </div>
            </div>
			<div class="form-group">
			    <label class="col-md-3 control-label" for="id_reponse">Réponse</label>
                <div class="col-md-6">
                    <input class="form-control" id="id_reponse" name="reponse" placeholder="Message" title="" type="text" />
                </div>
            </div>
            {% buttons layout="horizontal" %}
                <button type="submit" class="btn btn-primary">Envoyer</button>
            {% endbuttons %}
        </form>
    </div>
</div>

<div id="messages-content">
{% render_messages msgs show_tools=True show_deleted=True %}
</div>

<div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="panel panel-danger">
            <div class="panel-heading" id="confirm-delete-title">
                Supprimer un message
            </div>
            <div class="panel-body">
                <form action="#" method="post" role="form" id="confirm-delete-form">
                    {% csrf_token %}
                    {% bootstrap_form delete_form %}
                    {% buttons %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Confirmer</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                        </div>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="confirm-edit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="panel panel-primary">
            <div class="panel-heading" id="confirm-edit-title">
                Modifier un message
            </div>
            <div class="panel-body">
                <form action="#" method="post" role="form" id="confirm-edit-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label" for="id_corps">Message</label>
                        <input class="form-control" id="id_corps" maxlength="256" name="corps" placeholder="Message" required="required" title="" type="text" />
                    </div>
                    {% buttons %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Modifier</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                        </div>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'js/jquery.autocomplete.min.js' %}"></script>
<script type="text/javascript">
$('input[name="expediteur"]').autocomplete({
  serviceUrl: "{% url 'search-indicatif' evenement.slug %}",
  onSelect: function (data) {
    $('input[name="expediteur"]').val(data.data);
  }
});
$('input[name="destinataire"]').autocomplete({
  serviceUrl: "{% url 'search-indicatif' evenement.slug %}",
  onSelect: function (data) {
    $('input[name="destinataire"]').val(data.data);
  }
});
</script>
<script type="text/javascript">
/* This script set the action url of the deletion form */
$('#confirm-delete').on('show.bs.modal', function(e) {
    $('#confirm-delete-form').attr('action', $(e.relatedTarget).data('action'));
});
/* This script set the action url of the edit form */
$('#confirm-edit').on('show.bs.modal', function(e) {
    $('#confirm-edit-form').attr('action', $(e.relatedTarget).data('action'));
    var thread = $(e.relatedTarget).data('thread');
    var value = $('#thread-' + thread).html();
    var input = $('input[name="corps"]');
    input.val(value);
    /* Not working :'-( */
    //input.focus();
    //input.select();
});
</script>
<script type="text/javascript">
window.setInterval(function() {
    $.get("{% url 'last-messages' evenement.slug %}?deleted=1&tools=1", function(data, status) {
        $("#messages-content").html(data);
    });
}, 5000);
</script>
{% endblock %}

django/maincourante/templates/maincourante/message_angular.html
{% extends 'maincourante/base.html' %}

{% load static %}
{% load bootstrap3 %}
{% load message_tags %}

{% block saisitab %} class="active"{% endblock %}

{% block css %}

{{ block.super }}

<link rel="stylesheet" href="{% static 'css/autocomplete.css' %}">
<link rel="stylesheet" href="{% static "css/maincourante.css" %}">
<link rel="stylesheet" href="{% static "angucomplete-alt/angucomplete-alt.css" %}">

{% endblock %}

{% block content %}
<diV ng-app="maincouranteApp">
<div ng-controller="MainCtrl">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Saisie des messages</h4>
        </div>
        <div class="panel-body panel-body-md">
            <form class="form-horizontal">
            {% csrf_token %}
                <div class="form-group">
			    <label class="col-md-3 control-label" for="id_destinataire">Destinataire</label>
                <div class="col-md-6">
                        <angucomplete-alt id="receiver"
                                          placeholder="Destinataire"
                                          pause="100"
                                          selected-object="receiver"
                                          local-data="indicatifs"
                                          search-fields="name"
                                          title-field="name"
                                          minlength="1"
                                          focuson="onNewMessage"
                                          override-suggestions="true"
                                          template-url="{% static 'scripts/maincourante/directives/angucomplete-custom.html' %}"
                                          input-class="form-control form-control-small"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Expéditeur</label>
                    <div class="col-md-6">
                        <angucomplete-alt id="sender"
                                          placeholder="Expéditeur"
                                          pause="100"
                                          selected-object="sender"
                                          local-data="indicatifs"
                                          search-fields="name"
                                          title-field="name"
                                          ng-model="from"
                                          minlength="1"
                                          override-suggestions="true"
                                          input-class="form-control form-control-small"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Message</label>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="body" ng-model="body" placeholder="Message">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Réponse</label>
                    <div class="col-md-6">
                        <input  type="text" class="form-control" name="reponse" ng-model="response" placeholder="Réponse"/>
                    </div>
                </div>
                {% buttons layout="horizontal" %}
                        <button type="submit" ng-click="addMessage()" class="btn btn-primary">Envoyer</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
    <div ng-if="errorMessage" class="alert alert-danger">
        <a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Erreur - </strong> {$errorMessage$}
    </div>

    <messages ng-init="enableEditionMode();"/>

</div>
<div id="sound"></div>

{% endblock %}


{% block js_end %}

{{ block.super }}

<script>
    var csrf = '{{ csrf_token|escapejs }}';
    var api_url = '{% url 'api_v1_top_level' 'v1' %}';
    var message_directive_template_url = '{% static 'scripts/maincourante/directives/message.html' %}';
    var EVENEMENT = '{{ evenement.nom }}';
    var EVENEMENT_ID = '{{ evenement.id }}';
    var SOUND_MESSAGE_PATH = '{% static 'sound/sounds-949-you-wouldnt-believe.mp3' %}';
    function PlaySound() {
        document.getElementById("sound").innerHTML = "";
        document.getElementById("sound").innerHTML='<audio autoplay="autoplay"><source src="' + SOUND_MESSAGE_PATH + '" type="audio/mpeg" /></audio>';
    }

</script>

<script src="{% static "angular/angular.js" %}" ></script>
<script src="{% static "angular-route/angular-route.js" %}" ></script>
<script src="{% static "angular-animate/angular-animate.js" %}" ></script>
<script src="{% static "angular-resource/angular-resource.js" %}" ></script>
<script src="{% static "angular-bootstrap/ui-bootstrap.js" %}" ></script>
<script src="{% static "angular-bootstrap/ui-bootstrap-tpls.js" %}" ></script>
<script src="{% static "angucomplete-alt/angucomplete-alt.js" %}" ></script>
<script src="{% static "ng-focus-on/ng-focus-on.js" %}" ></script>

<script src="{% static "scripts/maincourante/entities/message.js" %}" ></script>
<script src="{% static "scripts/maincourante/entities/indicatif.js" %}" ></script>
<script src="{% static "scripts/maincourante/controllers/message_controller.js" %}" ></script>
<script src="{% static "scripts/maincourante/directives/message_directive.js" %}" ></script>
<script src="{% static "scripts/maincourante/app.js" %}" ></script>

{% endblock %}